#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e pulsemixer & ;;
	2) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
	3) pgrep -x dunst >/dev/null && notify-send "Volume: $(volume get)%"
esac

[ "$(pulsemixer --get-mute)" = "1" ] && printf "<span font_desc='Material Icons'>\Ue04f</span>" && exit

	vol=$(pulsemixer --get-volume | awk '{print $1}')

if [ "$vol" -gt "70" ]; then
	printf "<span font_desc='Material Icons'>\Ue050</span>" # volume_up
elif [ "$vol" -lt "20" ]; then
	printf "<span font_desc='Material Icons'>\Ue04e</span>" # volume_mute
else
	printf "<span font_desc='Material Icons'>\Ue04d</span>" # volume_down
fi

