#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e pulsemixer & ;;
	2) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
	3) pgrep -x dunst >/dev/null && notify-send "Volume: $(volume get)%"
esac

# Print the speaker icon
printf "<span bgcolor='#e06c75' fgcolor='#282c34'>  </span>"
[ "$(pulsemixer --get-mute)" = "1" ] && printf " muted" && exit

vol=$(pulsemixer --get-volume | awk '{print $1}')
printf ' %s%%' $vol
