#!/usr/bin/env zsh

# setup PATH etc
source $HOME/.zshrc

sxhkd &
compton -b &
notificator &
feh --bg-fill $HOME/.wallpaper.jpg &
xsetroot -cursor_name left_ptr &

bspc config border_width         1
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config focus_follows_pointer true

bspc monitor -d Code Web Trello Game Stuff

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Google-chrome desktop='^2'
# ~/.bspwm/bspwmrc
# bspwm config template
# Base16 Flat by Chris Kempson (http://chriskempson.com)
# template by Luke Jones @luke-nukem

bspc config active_border_color \#BDC3C7
bspc config normal_border_color \#7F8C8D
bspc config focused_border_color \#E74C3C
bspc config presel_feedback_color \#E74C3C
bspc config normal_locked_border_color \#2ECC71
bspc config focused_locked_border_color \#2ECC71
bspc config normal_sticky_border_color \#E67E22
bspc config focused_sticky_border_color \#E67E22
bspc config normal_private_border_color \#34495E
bspc config focused_private_border_color \#34495E

