#!/bin/sh

# Script to increment/decrement backlight brightness
# It currently uses brightnessctl to do so

DEFAULT_STEP=10

usage() {
	cat << EOH
brightness is a utility for modifying and querying the backlight brightness.
usage: brightness <command>, where <command> is one of:

increment [value]    increments the brightness by [value] steps
decrement [value]    decrements the brightness by [value] steps
get                  returns the current brightness in percent
help                 print this help text

Each command can be abbreviated to its shortest unique form.
There are $BRIGHTNESS_STEPS brightness steps available.
EOH
}

get_brightness() {
	brightnessctl info -m | tr ',' "\t" | awk '{ print $4 }'
}

update_brightness() {
	delta=$1
	brightnessctl set "$delta" > /dev/null
	logger -t BRIGHTNESS "Modifying brightness by $delta"
}

case $1 in
	i*)
		val=$2
		[ -z $val ] && val="$DEFAULT_STEP"
		update_brightness "$val%+"
		;;
	d*)
		val=$2
		[ -z $val ] && val="$DEFAULT_STEP"
		update_brightness "$val%-"
		;;
	g*)
		get_brightness
		;;
	h*)
		usage
		exit 0
		;;
	--help)
		usage
		exit 0
		;;
	*)
		usage
		exit 1
		;;
esac
