#!/bin/zsh

fontsize=12
center=false

while getopts cs: opt
do
 case $opt in
   s)
     fontsize=$OPTARG
     shift
     ;;
   c)
     center=true
     shift
     ;;
 esac
done

msg=$1

echo "msg: $1, fs: $fontsize, c: $center"

