#!/bin/sh

# Lets you pick a unicode character from a list and automatically types or copies it


# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 ~/.local/share/unicode-symbols | rofi -dmenu -i -l 30 -p 'Pick a symbol' | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
echo "$chosen" | tr -d '\n' | wl-copy
notify-send "'$chosen' copied to clipboard." &
