#!/bin/sh
#
# This script is triggered by a udev rule when I dock my thinkpad with its docking station
# udev will pass the action as the first parameter
#
# TODO: debouncing - for some reason, the script triggers twice when docking/undocking
# TODO: read monitor config from device specific settings


ACTION=$1

case $ACTION in
	add )
		DOCKED=1
		;;
	remove )
		DOCKED=0
		;;
	auto|thaw|resume )
		# Detect whether we're docked or not. This is used when waking up from sleep
		# 17ef:100f is the USB device ID of my thinkpad dock. Yours might have another ID.
		logger -t DOCKING "Auto-Detecting docking status"
		[ -z "$(lsusb | grep '17ef:100f')" ] && DOCKED=0 || DOCKED=1
		;;
	* )
		logger -t DOCKING "Could not interpret action '$ACTION'"
		exit 1
		;;
esac

set_displays() {
	export DISPLAY=":0"
	if [[ $DOCKED == 1 ]]; then
		sleep 1
		xrandr \
			--output DP2-1 --auto --scale 0.75x0.75 --primary --pos 1920x0
	else
		xrandr \
			--output DP2-1 --off
	fi
	logger -t DOCKING "Reconfigured monitors"
}

[ $DOCKED -eq 1 ] && logger -t DOCKING "We're docked" || logger -t DOCKING "We're undocked"

# 1. Update the displays
set_displays
# 2. Re-apply the wallpaper
locker.sh -w
# 3. Refresh xmodmap - For some reason, the external keyboard sometimes doesn't have the capslock
# disabled
xmodmap ~/.Xmodmap


