#!/bin/sh

COMMAND=$1

notify_i3blocks="pkill -RTMIN+10 i3blocks"

usage () {
  cat << EOF
usage: $0 <command>

commands:
	down <num> decreases the volume by <num> (default 5)
	up <num>   increase the volume by <num> (default 5)
  mute   		 toggle the mute state

All commands can be abbreviated, i.e. \'$0 d\' for \'$0 down 5\'.
This script also tries to notify i3blocks to update the volume block (signal 10)
EOF
}


case $COMMAND in
  u*)
		[ -z "$2" ] && vol="5" || vol="$2";
		pulsemixer --change-volume +"$vol";
		$notify_i3blocks;
    ;;
  d* )
		[ -z "$2" ] && vol="5" || vol="$2";
		pulsemixer --change-volume -"$vol";
		$notify_i3blocks;
		;;
  m* )
		pulsemixer --toggle-mute;
		$notify_i3blocks;
    ;;
  * )
    usage
    exit 1
    ;;
esac

