#!/bin/sh

COMMAND=$1

usage () {
	name=$(basename $0)
  cat << EOF
usage: $name <command>

commands:
	down <num> decreases the volume by <num> (default 5)
	up <num>   increase the volume by <num> (default 5)
	mute   		 toggle the mute state
	get        returns the current volume [0-100]

All commands can be abbreviated, i.e. '$name d' for '$name down 5'.
This script also tries to notify i3blocks to update the volume block (signal 10)
EOF
}

notify_i3blocks() {
	pkill -RTMIN+10 i3blocks
}


case $COMMAND in
  u* )
		[ -z "$2" ] && vol="5" || vol="$2";
		pulsemixer --change-volume +"$vol";
		notify_i3blocks
    ;;
  d* )
		[ -z "$2" ] && vol="5" || vol="$2";
		pulsemixer --change-volume -"$vol";
		notify_i3blocks
		;;
  m* )
		pulsemixer --toggle-mute;
		notify_i3blocks
    ;;
	g*)
		[ "0" -eq "$(pulsemixer --get-mute)" ] && echo "$(pulsemixer --get-volume | cut -d ' ' -f1)%" || echo 'muted'
		;;
  * )
    usage
    exit 1
    ;;
esac

